### ISSUE TITLE
Awesome progress bar endeavor

### ISSUE THREAD

**Issue by dryajov** [ipfs/js-ipfs-api#608]
This issues is here to track the progress bar functionality effort

## Tasks required to complete this endeavor:

- [x] Document this feature in spec https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#files-api
- [x] Create big file and directory tests
- [x] Move tests to https://github.com/ipfs/interface-ipfs-core/tree/master/src
- [x] Test against js-ipfs too
- [x] Make sure that when linked, js-ipfs CLI picks up on this to show the progress bar.

## Relevant PRs

| Name | Ready for Review | Reviewed | Merged | Published | 
|-------|-------------------|---------|---------|-----------|
|[interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core/pull/158) |✅|✅|✅|✅|
|[js-ipfs](https://github.com/ipfs/js-ipfs/pull/1036) |✅|✅|✅|❌|
|[js-ipfs-api](https://github.com/ipfs/js-ipfs-api/pull/604) |✅|✅|✅|✅|

### Additional notes

With the introduction of errors through the Trailer header, we have ran into an issue described here -
 https://github.com/ipfs/js-ipfs-api/issues/607. This shouldn't block this endeavor, but should be resolved ASAP.

Tagging @diasdavid

**Comment by VictorBjelkholm** [comment]
Updated the table to reflect that the interface-ipfs-core tests have been merged and published already.

**Comment by dryajov** [comment]
We'll need to make another release of interface-ipfs-core tho, there are some discrepancies with js-ipfs and go-ipfs reporting that I let slip, which cause the tests fail under js-ipfs. I have a patch coming soon.

**Comment by dryajov** [comment]
@diasdavid 

This issue (https://github.com/ipfs/js-ipfs/pull/1036), is also ready for another review pass. In general, all required functionality has been implemented and tests are passing with latest interface-ipfs-core and ipfs-api.

I left this comment regarding some possible code duplication here - https://github.com/ipfs/js-ipfs/pull/1036#pullrequestreview-70362921.

Also, https://github.com/ipfs/js-ipfs/pull/1036/commits/bd70fbd92c8c977f1bd5a212fcc5c4a741908f18 fixes an issue with js-ipfs, were it never actually sent the `Size` of the file in the json structure, which is breaking with the latest changes in js-ipfs-api (https://github.com/ipfs/js-ipfs-api/commit/0ea5f57c0991b48d9ea1c0161d8bd047aeb2aca0#diff-ecdce0998c1946cbd6351a8c47ca9eb7R37).

**Comment by diasdavid** [comment]
Woot! All merged :D This feature will come out in the next js-ipfs release. Thank you @dryajov <3

> I left this comment regarding some possible code duplication here - ipfs/js-ipfs#1036 (review).

Please handle this with https://github.com/ipfs/js-ipfs/issues/1041

**Comment by lidel** [comment]
Is it compatible with `go-ipfs` v0.4.11, or do we need to wait for  v0.4.12?

**Comment by diasdavid** [comment]
It should work today! The change wasn't in go-ipfs, it was just js-ipfs-api.
